# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AqiReport(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, date=None, time=None, pm25=None, air_quality=None):  # noqa: E501
        """AqiReport - a model defined in OpenAPI

        :param date: The date of this AqiReport.  # noqa: E501
        :type date: str
        :param time: The time of this AqiReport.  # noqa: E501
        :type time: str
        :param pm25: The pm25 of this AqiReport.  # noqa: E501
        :type pm25: float
        :param air_quality: The air_quality of this AqiReport.  # noqa: E501
        :type air_quality: str
        """
        self.openapi_types = {
            'date': str,
            'time': str,
            'pm25': float,
            'air_quality': str
        }

        self.attribute_map = {
            'date': 'date',
            'time': 'time',
            'pm25': 'pm25',
            'air_quality': 'airQuality'
        }

        self._date = date
        self._time = time
        self._pm25 = pm25
        self._air_quality = air_quality

    @classmethod
    def from_dict(cls, dikt) -> 'AqiReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AqiReport of this AqiReport.  # noqa: E501
        :rtype: AqiReport
        """
        return util.deserialize_model(dikt, cls)

    @property
    def date(self):
        """Gets the date of this AqiReport.


        :return: The date of this AqiReport.
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this AqiReport.


        :param date: The date of this AqiReport.
        :type date: str
        """

        self._date = date

    @property
    def time(self):
        """Gets the time of this AqiReport.


        :return: The time of this AqiReport.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this AqiReport.


        :param time: The time of this AqiReport.
        :type time: str
        """

        self._time = time

    @property
    def pm25(self):
        """Gets the pm25 of this AqiReport.


        :return: The pm25 of this AqiReport.
        :rtype: float
        """
        return self._pm25

    @pm25.setter
    def pm25(self, pm25):
        """Sets the pm25 of this AqiReport.


        :param pm25: The pm25 of this AqiReport.
        :type pm25: float
        """

        self._pm25 = pm25

    @property
    def air_quality(self):
        """Gets the air_quality of this AqiReport.


        :return: The air_quality of this AqiReport.
        :rtype: str
        """
        return self._air_quality

    @air_quality.setter
    def air_quality(self, air_quality):
        """Sets the air_quality of this AqiReport.


        :param air_quality: The air_quality of this AqiReport.
        :type air_quality: str
        """

        self._air_quality = air_quality
