# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TmdReport(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, date=None, time=None, rainfall=None, rain_status=None):  # noqa: E501
        """TmdReport - a model defined in OpenAPI

        :param date: The date of this TmdReport.  # noqa: E501
        :type date: str
        :param time: The time of this TmdReport.  # noqa: E501
        :type time: str
        :param rainfall: The rainfall of this TmdReport.  # noqa: E501
        :type rainfall: float
        :param rain_status: The rain_status of this TmdReport.  # noqa: E501
        :type rain_status: str
        """
        self.openapi_types = {
            'date': str,
            'time': str,
            'rainfall': float,
            'rain_status': str
        }

        self.attribute_map = {
            'date': 'date',
            'time': 'time',
            'rainfall': 'rainfall',
            'rain_status': 'rainStatus'
        }

        self._date = date
        self._time = time
        self._rainfall = rainfall
        self._rain_status = rain_status

    @classmethod
    def from_dict(cls, dikt) -> 'TmdReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TmdReport of this TmdReport.  # noqa: E501
        :rtype: TmdReport
        """
        return util.deserialize_model(dikt, cls)

    @property
    def date(self):
        """Gets the date of this TmdReport.


        :return: The date of this TmdReport.
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this TmdReport.


        :param date: The date of this TmdReport.
        :type date: str
        """

        self._date = date

    @property
    def time(self):
        """Gets the time of this TmdReport.


        :return: The time of this TmdReport.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this TmdReport.


        :param time: The time of this TmdReport.
        :type time: str
        """

        self._time = time

    @property
    def rainfall(self):
        """Gets the rainfall of this TmdReport.


        :return: The rainfall of this TmdReport.
        :rtype: float
        """
        return self._rainfall

    @rainfall.setter
    def rainfall(self, rainfall):
        """Sets the rainfall of this TmdReport.


        :param rainfall: The rainfall of this TmdReport.
        :type rainfall: float
        """

        self._rainfall = rainfall

    @property
    def rain_status(self):
        """Gets the rain_status of this TmdReport.


        :return: The rain_status of this TmdReport.
        :rtype: str
        """
        return self._rain_status

    @rain_status.setter
    def rain_status(self, rain_status):
        """Sets the rain_status of this TmdReport.


        :param rain_status: The rain_status of this TmdReport.
        :type rain_status: str
        """

        self._rain_status = rain_status
